---
title: "Life expectancy"
output: html_document
---
```{r}
setwd("data-analysis/")
library(ggplot2)
library(gridExtra)
library(grid)
library(dplyr); library(tidyr)
life_expectancy <- read.csv("life_expectancy.csv")
gdp <- read.csv("gdp_per_capita.csv")
life_expectancy <- tbl_df(life_expectancy)
gdp <- tbl_df(gdp)
```

##Transposing life_expectancy table
```{r}
life_expectancy <- life_expectancy %>% gather("Year", "Life expectancy", -1) %>% spread("Country", "Life expectancy") 
head(life_expectancy)
```

##Removing "X" in front of years
```{r}
years <- life_expectancy$Year
count = 1

for (year in years){
  life_expectancy$Year[count] <- substr(year, 2,5)
  count = count + 1
}
```

##Transposing gdp table
```{r}
gdp <- gdp %>% gather("Year", "GDP", -1) %>% spread("Country", "GDP") 
head(gdp)
```

##Removing "X" in front of years
```{r}
rm(years, count, year)
years <- gdp$Year
count = 1

for (year in years){
  gdp$Year[count] <- substr(year, 2,5)
  count = count + 1
}
```

##Plot of life expectancy in Germany over the last 50 years
```{r}
p1 <- ggplot(aes(y=Germany, x = Year, group = 1), data = subset(life_expectancy, life_expectancy$Year > "1945")) + 
  geom_point(stat = "summary", fun.y = max, colour="#099dd9",size=2) + stat_summary(fun.y = max, geom="line") +geom_smooth(color="#9dd999") + xlab("Life expectancy in years") + ggtitle("Life expectancy in Germany from 1946 - 2013") 

p1
```
##Life expectancy in the US
```{r}
p2 <- ggplot(aes(y=`United States`, x = Year, group = 1), data = subset(life_expectancy, life_expectancy$Year > "1945")) + 
  geom_point(stat = "summary", fun.y = max, colour="#f79420",size=2) + stat_summary(fun.y = max, geom="line") +geom_smooth(color="#9dd999") + xlab("Life expectancy in years") + ggtitle("Life expectancy in the US from 1946 - 2013") 

```
##China
```{r}
p3 <- ggplot(aes(y=`China`, x = Year, group = 1), data = subset(life_expectancy, life_expectancy$Year > "1945")) + 
  geom_point(stat = "summary", fun.y = max, colour="red",size=2) + stat_summary(fun.y = max, geom="line") +geom_smooth(color="#9dd999") + xlab("Life expectancy in years") + ggtitle("Life expectancy in China from 1946 - 2013") 

grid.arrange(p1,p2,p3, ncol=1)
```
##Madagascar
```{r}

p4 <- ggplot(aes(y=Madagascar, x = Year, group = 1), data = subset(life_expectancy, life_expectancy$Year > "1945")) + 
  geom_point(stat = "summary", fun.y = max, colour="#099dd9",size=2) + stat_summary(fun.y = max, geom="line") +geom_smooth(color="#9dd999") + xlab("Life expectancy in years") + ggtitle("Life expectancy in Madagascar from 1946 - 2013") 

grid.arrange(p1,p2,p3,p4, ncol=1)
```
##Somalia
```{r}
p5 <- ggplot(aes(y=Somalia, x = Year, group = 1), data = subset(life_expectancy, life_expectancy$Year > "1945")) + 
  geom_point(colour="#099dd9",size=2) + geom_line() + +geom_smooth(color="#9dd999") + xlab("Life expectancy in years") + ggtitle("Life expectancy in Somalia from 1946 - 2013") 

grid.arrange(p1,p5, p2,p3,p4, ncol=1)
ggsave(filename = "Life expectancy of various countries.png")
```

```{r}

g1 <- ggplot(aes(x=Year, y = Germany, group = 1), data=subset(gdp, !is.na(Germany))) + geom_line() + geom_point() + geom_smooth() + ylab("GDP") + ggtitle("GDP Germany 1970 - 2011")

g2 <- ggplot(aes(x=Year, y = `United States`, group = 1), data=subset(gdp, !is.na(`United States`))) + geom_line() + geom_point() + geom_smooth() + ylab("GDP") + ggtitle("GDP USA 1960 - 2011")

g3 <- ggplot(aes(x=Year, y = China, group = 1), data=subset(gdp, !is.na(China))) + geom_line() + geom_point() + geom_smooth() + ylab("GDP") + ggtitle("GDP China 1960 - 2011")

g4 <- ggplot(data=gdp, aes(x=Year), group=1) + geom_point(aes(y=Germany), colour="#099dd9", group=1, shape=1) +
  geom_line(aes(y=Germany), group = 1, colour='#f79420') + ylab("GDP")

g4 <- g4 + geom_point(aes(y=`United States`), group=2, shape=2) +
  geom_line(aes(y=`United States`), group = 2, colour='green') + ylab("GDP")  

g4 <- g4 + geom_point(aes(y=China), colour="red", group=3, shape=4) +
  geom_line(aes(y=China), group = 3, colour='black') + ylab("GDP") 



grid.arrange(g1,g2,g3,g4,ncol=1)

ggsave("GDP Germany, USA, China line chart.png")

```
##Multiple plots in one + legend
```{r}
df <- data.frame(Year = gdp$Year, Germany = gdp$Germany, USA = gdp$`United States`, China = gdp$China, Russia = gdp$Russia)
df.melted <- melt(df,id="Year")

ggplot(df.melted, aes(x=Year, y = value, color = factor(variable)))+
  geom_point(shape = 1) +
  ylab("GDP") +
  scale_y_continuous(breaks=seq(0,40000,2500)) +
  scale_colour_discrete(name = "Country")

ggsave("GDP Multiple Countries in 1 plot - scatter plot.png")
```
```{r}
df <- data.frame(Year = gdp$Year, Germany = gdp$Germany, USA = gdp$`United States`, China = gdp$China, Russia = gdp$Russia)

ggplot(df, aes(x=Year, y = value, color = Country)) + 
  geom_line(aes(y=Germany, col="Germany"), group=1) +
  geom_point(aes(y=Germany, col="Germany")) +
  geom_line(aes(y=USA, col="USA"), group=2) +
  geom_point(aes(y=USA, col="USA")) +
  geom_line(aes(y=China, col="China"), group=3) +
  geom_point(aes(y=China, col="China")) +
  geom_line(aes(y=Russia, col="Russia"), group=4) +
  geom_point(aes(y=Russia, col="Russia")) +
  ylab("GDP") +
  scale_y_continuous(breaks=seq(0,40000,2500)) +
  scale_colour_discrete(name = "Country") + 
  ggtitle("GDP of the countries China, Germany, Russia and USA\nfrom 1960 until 2011")

ggsave("GDP Multiple Countries in 1 plot - line plot.png")
```

